
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/lesson82.ipynb

# standard libraries
from pathlib import Path
from IPython.core.debugger import set_trace
import pickle, gzip, math, torch, matplotlib as mpl
import matplotlib.pyplot as plt

# datasets
from fastai import datasets

# basic pytorch
from torch import tensor

MNIST_URL='http://deeplearning.net/data/mnist/